SERIAL_DRIVER = vendor
COMBO_ENABLE = no
COMBO_SHOULD_TRIGGER = no
KEY_OVERRIDE_ENABLE = no
SEND_STRING_ENABLE = yes
OS_DETECTION_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
LTO_ENABLE = yes
TAP_DANCE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no

MOUSEKEY_ENABLE = yes
SPLIT_KEYBOARD = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
# SOLENOID
HAPTIC_ENABLE = yes
HAPTIC_DRIVER = solenoid
SOLENOID_ENABLE = yes
# OLED
OLED_ENABLE = yes
# CIRQUE TRACKPAD
POINTING_DEVICE_ENABLE = yes
SPI_DRIVER_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
# RGB
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
TOUS_LES_EFFETS_RGB = yes




OPT_DEFS += -DTOUS_LES_EFFETS_RGB
ifeq ($(TOUS_LES_EFFETS_RGB), yes)
    OPT_DEFS += -DTOUS_LES_EFFETS_RGB
endif