# SERIAL_DRIVER = usart
SERIAL_DRIVER = vendor
# mes rules custom
# TODO ACTIVATE COMBOS
COMBO_ENABLE = yes
COMBO_SHOULD_TRIGGER = yes
# TODO ACTIVATE OVERRIDE
KEY_OVERRIDE_ENABLE = yes
SEND_STRING_ENABLE = yes
OS_DETECTION_ENABLE = yes
# UNICODE_COMMON = yes
# RGB_MATRIX_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
LTO_ENABLE = yes
# TODO ACTIVATE TAP_DANCE
TAP_DANCE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
# VIA_ENABLE = YES
OLED_ENABLE = yes
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
MOUSEKEY_ENABLE = yes
SPLIT_KEYBOARD = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# SOLENOID
HAPTIC_ENABLE = yes
HAPTIC_DRIVER = solenoid

# BOOTLOADER = rp2040
# CONVERT_TO = rp2040_ce

SRC += accents.c
SRC += gaming.c
SRC += numpad.c
SRC += web.c
SRC += globals.c
SRC += oled.c
